package com.smk627751.zcart.dto

val genericCategories = listOf(
    "Electronics",
    "Fashion",
    "Clothing",
    "Footwear",
    "Home and Kitchen",
    "Groceries"
)
val specificCategories = listOf(
    "Electronics",
    "Mobile Phones",
    "Laptops",
    "Cameras",
    "Audio & Headphones",
    "Wearable Technology",
    "Fashion",
    "Men's Clothing",
    "Women's Clothing",
    "Footwear",
    "Accessories",
    "Handbags",
    "Home and Kitchen",
    "Furniture",
    "Kitchen Appliances",
    "Bedding",
    "Home Decor",
    "Cookware",
    "Beauty and Personal Care",
    "Skincare",
    "Hair Care",
    "Makeup",
    "Fragrances",
    "Men's Grooming",
    "Health and Wellness",
    "Vitamins & Supplements",
    "Fitness Equipment",
    "Personal Care Appliances",
    "Medical Supplies",
    "Diet & Nutrition",
    "Books and Media",
    "Fiction",
    "Non-Fiction",
    "Children's Books",
    "Magazines",
    "E-Books",
    "Sports and Outdoors",
    "Exercise & Fitness",
    "Outdoor Recreation",
    "Sports Equipment",
    "Camping & Hiking",
    "Cycling",
    "Toys and Games",
    "Educational Toys",
    "Action Figures",
    "Dolls & Accessories",
    "Board Games",
    "Puzzles",
    "Automotive",
    "Car Accessories",
    "Motorcycle Parts",
    "Car Care",
    "Tools & Equipment",
    "Tires & Wheels",
    "Pet Supplies",
    "Dog Supplies",
    "Cat Supplies",
    "Fish & Aquatic Pets",
    "Small Animal Supplies",
    "Bird Supplies",
    "Groceries",
    "Snacks & Beverages",
    "Organic Foods",
    "Baking Essentials",
    "Canned Goods",
    "Condiments & Sauces",
    "Office Supplies",
    "Writing & Correction",
    "Paper Products",
    "Desk Accessories",
    "Filing & Storage",
    "Office Electronics",
    "Baby Products",
    "Diapers & Wipes",
    "Baby Gear",
    "Nursery Furniture",
    "Feeding & Nursing",
    "Baby Toys",
    "Garden and Outdoor",
    "Gardening Tools",
    "Outdoor Furniture",
    "Grills & Outdoor Cooking",
    "Plants & Seeds",
    "Lawn Care",
    "Jewelry and Watches",
    "Men's Watches",
    "Women's Watches",
    "Necklaces",
    "Rings",
    "Earrings"
)
